name: Diff

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Diff
        id: diff
        uses: ./
      - name: Show
        run: echo ${{ steps.diff.outputs.diff }}